### ISSUE TITLE
"Examples" page?

### ISSUE THREAD

**Issue by Pyrobolser** [siimple/website#6]
Hello,

Not really an issue and more of a question.
Do you plan on adding some common examples to your documentation website?
Like Bootstrap did on https://getbootstrap.com/docs/4.0/examples/

I am not really a front-end guy and I wanted to find something easy and clear to use that was lighter than Boostrap & Co. and Siimple looks like a nice alternative but the lack of examples that only use Siimple and nothing else (like that plume.css file that seems to be everywhere) makes it kinda hard to grasp.

Maybe I am missing some CSS knowledge but I still wanted to ask the question!

Thanks,

**Comment by jmjuanes** [comment]
Hello @Pyrobolser 

Thanks for your question! The answer is yes, I am working on a set of examples using siimple that will be available in `v3.1.0` (today I have published `v3.1.0-beta.3`, the last of the betas releases). Also, the new version will come with a more detailed documentation.

If you have any question about how to use siimple, I will be happy to help you :smile:

**Comment by Pyrobolser** [comment]
Thank you for your answer.
I will be excited to see what's new on the new examples and documentation when you release it then!
That's really nice of you to offer to help if I have any question, I won't hesitate if I can't figure something out by myself.

Have a great week,

**Comment by jmjuanes** [comment]
Hello @Pyrobolser 
I have just published the new version `3.1.0`. You can find examples in the documentation website: https://docs.siimple.xyz/

**Comment by Pyrobolser** [comment]
Hey thank you, appreciate it, I'll check it out :)
